#!/usr/bin/env node

/*! Copyright Twitter Inc. and other contributors. Licensed under MIT *//*
    https://github.com/twitter/twemoji/blob/gh-pages/LICENSE
*/

const fs = require('fs-extra');
const path = require('path');
const { spawnSync } = require('child_process');
const { getIntegrityHash } = require('./utils');

function file(...which) {
  return path.join(__dirname, '..', ...which);
}

function distFile(...which) {
  return path.join(__dirname, '..', 'dist', ...which);
}

fs.writeFileSync(
  distFile('phemoji.npm.js'),
  [
    'var location = global.location || {};',
    fs.readFileSync(distFile('phemoji.js')),
    'if (!location.protocol) {',
    '  phemoji.base = phemoji.base.replace(/^http:/, "");',
    '}',
    'module.exports = phemoji;'
  ].join('\n')
);

fs.writeFileSync(
  distFile('phemoji.amd.js'),
  'define(function () {\n' +
    fs.readFileSync(distFile('phemoji.js')).toString().replace(
      /^(.)/gm, '  $1'
    ) +
  '\n  return phemoji;\n});'
);

spawnSync(
  'yarn',
  [
    'uglifyjs',
    '--verbose',
    distFile('phemoji.js'),
    '-o',
    distFile('phemoji.tmp.js')
  ]
);

const copyright = '/*! Copyright Twitter Inc. and other contributors. Licensed under MIT */';
const minifiedContents = fs.readFileSync(distFile('phemoji.tmp.js'));
fs.unlinkSync(distFile('phemoji.tmp.js'));

fs.writeFileSync(distFile('phemoji.min.js'), `${copyright}\n${minifiedContents}`);
fs.writeFileSync(distFile('phemoji.esm.js'), `${copyright}\n${minifiedContents}\nexport default phemoji;`);

const integrityHash = getIntegrityHash(distFile('phemoji.min.js'));
const { version } = require('../package.json');

function updateSriScriptReference(filename) {
  const newScript = `<script src="https://unpkg.com/twemoji@${version}/dist/twemoji.min.js" integrity="${integrityHash}"`;
  fs.writeFileSync(filename, fs.readFileSync(filename).toString('utf8').replace(/<script src="[^ ]*" integrity="[^ ]*"/, newScript));
}

updateSriScriptReference(file('README.md'));

// Copy the png assets and svgs to the dist folder
fs.copySync(file('assets/svg'), distFile('svg'));
fs.copySync(file('assets/72x72'), distFile('72x72'));